import { parseGpl, serializeGpl } from '../../../src/shared/palette-formats/gimpGpl';
import { PaletteParseError } from '../../../src/shared/palette-formats/types';

const VALID_GPL = [
  'GIMP Palette',
  'Name: My Palette',
  'Columns: 4',
  '# Generated by Palettax',
  '255   0   0\tRed',
  '  0 255   0\tGreen',
  '  0   0 255\tBlue',
  '255 255 255\tWhite'
].join('\n');

describe('parseGpl', () => {
  it('parsea Name, Columns y colores con nombre, ignorando comentarios', () => {
    const palette = parseGpl(VALID_GPL, '/tmp/test.gpl');
    expect(palette.name).toBe('My Palette');
    expect(palette.columns).toBe(4);
    expect(palette.colors).toHaveLength(4);
    expect(palette.colors[0]).toMatchObject({ r: 255, g: 0, b: 0, name: 'Red' });
    expect(palette.colors[3]).toMatchObject({ r: 255, g: 255, b: 255, name: 'White' });
  });

  it('usa el nombre de fichero si no hay línea Name:', () => {
    const content = ['GIMP Palette', '255 0 0 Red'].join('\n');
    const palette = parseGpl(content, '/tmp/sin-nombre.gpl');
    expect(palette.name).toBe('sin-nombre');
  });

  it('lanza PaletteParseError si falta la cabecera GIMP Palette', () => {
    expect(() => parseGpl('not a gpl file', 'test.gpl')).toThrow(PaletteParseError);
  });
});

describe('serializeGpl', () => {
  it('preserva Name, Columns y nombres de color', () => {
    const palette = parseGpl(VALID_GPL, 'test.gpl');
    const serialized = serializeGpl(palette);
    expect(serialized).toContain('Name: My Palette');
    expect(serialized).toContain('Columns: 4');
    expect(serialized).toContain('Red');
  });

  it('hace round-trip manteniendo colores, nombres y orden', () => {
    const original = parseGpl(VALID_GPL, 'test.gpl');
    const roundTripped = parseGpl(serializeGpl(original), 'test.gpl');
    expect(roundTripped.colors.map(({ r, g, b, name }) => ({ r, g, b, name }))).toEqual(
      original.colors.map(({ r, g, b, name }) => ({ r, g, b, name }))
    );
  });
});
